services:
  database:
    image: mysql:latest
    container_name: db_mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: db_dashboard
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - "8080:80"
    networks:
      - network

networks:
  network:

volumes:
  db_data:
